# Generated by Django 5.1.3 on 2024-12-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hname', models.CharField(max_length=100)),
                ('hdesc', models.TextField()),
                ('himg', models.ImageField(upload_to='hotel_image/')),
            ],
        ),
    ]
